### PR TITLE
Improve logging for lcov parser when coverage report is inconsistent

### LINKED ISSUE #776: Improve logging for lcov parser when coverage report is inconsistent
**I want to request a feature.**
Make the logging of problems with the parsing of LCOV consistent with SonarJS 

In SonarJS the parser was changed so it will log problems with level _[DEBUG]_.
In SonarTS this is not (yet) implemented and it will log problems with level _[WARNING]_.

**For SonarJS**
Originally reported: https://github.com/SonarSource/SonarJS/issues/942
Addressed in: https://github.com/SonarSource/SonarJS/pull/1018

### PR DESCRIPTION
**Pull request by SeyVaneerdewegh**
Made consistent with SonarJS - github.com/SonarSource/SonarJS/pull/1018

Fixes #776

### CODE REVIEW

**Comment by vilchik-elena** [comment]
@SeyVaneerdewegh thanks for PR! 

I have one concern related to the code duplication. In fact logic of report import is exactly the same in SonarJS so it would make sense to refactor it in a shared code (for example as part of https://github.com/SonarSource/sonar-analyzer-commons).

Yet probably we can merge this PR as a temporary thing.

When we will start sprint on SonarTS we will decide and either fix #776 by relying on shared with SonarJS lib or merge your PR.

**Comment by SeyVaneerdewegh** [comment]
@vilchik-elena Yes I agree it would be better to use the common lib and refactor the shared code.

I myself was not aware of the sonar-analyzer-commons package nor was I comfortable to change both plugins and introduce a common package.

When will the next sprint start?

**Comment by vilchik-elena** [comment]
@SeyVaneerdewegh no idea:(

**Comment by SeyVaneerdewegh** [comment]
@vilchik-elena Oh, ok.
Is there any possibility we can get this PR merged as a temporary thing like suggested?

**Pull request merged**
