### PR TITLE
Remove dependency on guava

### PR DESCRIPTION
**Pull request by dbmeneses**
As part of MMF-1121.
2.4 -> 1.6 MB

### CODE REVIEW

**Comment by inverno** [comment]
@vilchik-elena have a look at the changes to the LCOV, I think all is fine, but I don't know if there was a specific need for all those `Maps.newHashMap()`

**Comment by dbmeneses** [comment]
@inverno It was just for convenience, as written in their javadoc:

> Note for Java 7 and later: this method is now unnecessary and should be treated as deprecated. Instead, use the HashMap constructor directly, taking advantage of the new "diamond" syntax.

**Comment by inverno** [comment]
@dbmeneses wdyt of https://next.sonarqube.com/sonarqube/project/issues?branch=dm%2Fremove_guava&id=sonarts&open=AWANZEzKhimKoCd2uRTU&resolved=false , fix or ignore?

**Comment by dbmeneses** [comment]
@inverno I'll fix it

**Pull request merged**
